USE ecommerce_mobili;
INSERT INTO utente (nome, cognome, id_ruolo) VALUES ('Jacopo', 'Corbani', 2);
INSERT INTO credenziali (nome_utente, password_utente, id_utente) VALUES ('jacopocorbani', '$2y$10$EmSbNtztnB7zmUD3ijYob.cq8h5sQbbtZInA1DzWSZYUw.ctKMhv2', 1);

INSERT INTO prodotti(id, nome, descrizione, prezzo, id_categoria) VALUES
	(1,'Divano Moderno', 'Elegante e confortevole, il divano moderno in pelle aggiunge stile contemporaneo al tuo spazio abitativo.', 1200.00, 1),
	(2,'Letto Matrimoniale', 'Un letto matrimoniale in legno massello per notti serene, con un design che unisce comfort e estetica moderna.', 800.00, 2),
	(3,'Lampada da Tavolo', 'Illumina con stile ogni angolo della tua casa con questa raffinata lampada da tavolo in stile industriale.', 70.00, 3),
	(4,'Tavolo da Pranzo', 'Riunisci famiglia e amici attorno a questo tavolo da pranzo in rovere, unendo funzionalità e design moderno.', 600.00, 4),
	(5,'Sedia da Ufficio', 'Confortevole e funzionale, la sedia da ufficio ergonomica offre supporto per lunghe ore di lavoro.', 150.00, 5),
	(6,'Armadio a Due Ante', 'Organizza il tuo spazio con questo elegante armadio a due ante in legno di pino.', 500.00, 6),
	(7,'Poltrona Reclinabile', 'Rilassati in totale comfort con questa poltrona reclinabile in tessuto, ideale per momenti di puro relax.', 250.00, 7),
	(8,'Credenza Vintage', 'Aggiungi un tocco retrò al tuo arredamento con questa credenza vintage in legno massello.', 700.00, 8),
	(9,'Libreria a Muro', 'Esponi i tuoi libri con stile su questa libreria a muro in metallo e legno, un\'opzione pratica e decorativa.', 200.00, 9),
	(10,'Scaffale Metallico', 'Robusto e moderno, lo scaffale metallico offre un\'opzione di stoccaggio resistente e contemporanea per il garage.', 100.00, 10),
	(11,'Cassettiera Bianca', 'Organizza con stile con questa cassettiera bianca con 5 cassetti, un elemento pratico per ogni stanza.', 80.00, 11),
	(12,'Mobile da Bagno', 'Funzionale e moderno, il mobile da bagno con specchio offre spazio di archiviazione e un design accattivante.', 300.00, 12),
	(13,'Tavolo da Giardino', 'Goditi il tuo spazio esterno con questo tavolo da giardino in rattan, perfetto per pranzi all\'aperto e momenti di relax.', 120.00, 13),
	(14,'Divano Chesterfield', 'Un\'icona di eleganza, il divano Chesterfield in pelle aggiunge un tocco di classe e comfort al tuo salotto.', 1500.00, 1),
	(15,'Letto Singolo', 'Compatto e accogliente, il letto singolo con contenitore è ideale per camere più piccole o come soluzione per gli ospiti.', 400.00, 2),
	(16,'Lampada da Terra', 'Illumina il tuo spazio con stile grazie a questa lampada da terra in stile moderno.', 90.00, 3),
	(17,'Tavolino da Caffè', 'Aggiungi un tocco di praticità al tuo salotto con questo tavolino da caffè in vetro, perfetto per riunioni informali.', 200.00, 4),
	(18,'Sedia da Pranzo', 'Comfort e stile si fondono in questa sedia da pranzo in legno massello, ideale per creare un\'atmosfera accogliente a tavola.', 60.00, 5),
	(19,'Armadio a Tre Ante', 'Massimo spazio e stile con questo armadio a tre ante in legno di quercia, perfetto per organizzare il tuo guardaroba.', 800.00, 6),
	(20,'Poltrona da Lettura', 'Un\'oasi di comfort, la poltrona da lettura in tessuto offre un luogo accogliente per immergersi nei tuoi libri preferiti.', 300.00, 7),
	(21,'Divano in Tessuto', 'Confortevole e moderno, il divano in tessuto color grigio aggiunge calore e stile al tuo soggiorno.', 900.00, 1),
	(22,'Letto a Castello', 'Ottimizza lo spazio con questo pratico letto a castello in metallo, ideale per camere con più occupanti.', 500.00, 2),
	(23,'Lampada da Soffitto', 'Illumina con eleganza ogni angolo della tua casa con questa lampada da soffitto a LED.', 120.00, 3),
	(24,'Tavolo da Cucina', 'Funzionale e accattivante, il tavolo da cucina in acciaio inossidabile è il cuore della tua area gastronomica.', 350.00, 4),
	(25,'Sedia da Giardino', 'Coniuga comodità e resistenza con questa sedia da giardino in plastica, perfetta per momenti all\'aria aperta.', 30.00, 5),
	(26,'Armadio a Quattro Ante', 'Massimo spazio di archiviazione con stile, grazie a questo ampio armadio a quattro ante in legno di faggio.', 1000.00, 6),
	(27,'Poltrona da Ufficio', 'Coniuga comfort e design nella tua area lavorativa con questa poltrona da ufficio in pelle.', 200.00, 7),
	(28,'Credenza Moderna', 'Unisce funzionalità e design contemporaneo, la credenza moderna in MDF è perfetta per l\'organizzazione degli spazi.', 400.00, 8),
	(29,'Libreria a Colonna', 'Ottimizza lo spazio verticale con questa libreria a colonna in legno massello, ideale per esporre libri e oggetti d\'arte.', 250.00, 9),
	(30,'Scaffale in Plastica', 'Leggero e pratico, lo scaffale in plastica offre soluzioni di stoccaggio flessibili in ogni ambiente domestico.', 50.00, 10),
	(31,'Cassettiera in Legno', 'Organizza con stile con questa cassettiera in legno con 3 cassetti, un elemento versatile per diverse stanze.', 120.00, 11),
	(32,'Mobile da Bagno Moderno', 'Unisce funzionalità e design contemporaneo, il mobile da bagno moderno con lavabo è perfetto per lo spazio dedicato all\'igiene personale.', 450.00, 12),
	(33,'Sedia da Giardino', 'Confortevole e resistente alle intemperie, la sedia da giardino in legno è l\'ideale per godersi gli spazi esterni.', 80.00, 13),
	(34,'Divano Classico', 'Elegante e raffinato, il divano classico in tessuto aggiunge un tocco di tradizione al tuo salotto.', 700.00, 1),
	(35,'Letto Singolo Moderno', 'Letto singolo moderno con contenitore, perfetto per ottimizzare lo spazio con stile contemporaneo.', 300.00, 2),
	(36,'Lampada da Parete', 'Illumina con eleganza ogni angolo con la lampada da parete a LED, un elemento moderno e funzionale.', 50.00, 3),
	(37,'Tavolo da Caffè Moderno', 'Tavolo da caffè moderno in vetro, un\'opzione chic per arricchire il tuo salotto con stile.', 150.00, 4),
	(38,'Sedia da Pranzo Moderna', 'Sedia da pranzo moderna in legno, unisce comfort e design contemporaneo per cene indimenticabili.', 40.00, 5),
	(39,'Armadio a Cinque Ante', 'Massimo spazio e stile con l\'armadio a cinque ante in legno di faggio, perfetto per organizzare la tua stanza.', 1200.00, 6),
	(40,'Poltrona da Ufficio Moderna', 'Confortevole e professionale, la poltrona da ufficio moderna in pelle rende il lavoro più piacevole.', 180.00, 7),
	(41,'Credenza Classica', 'Credenza classica in legno massello, un pezzo d\'arredamento che aggiunge charme e praticità.', 500.00, 8),
	(42,'Libreria a Terra', 'Esponi i tuoi libri con stile su questa libreria a terra in metallo e legno, perfetta per un tocco moderno.', 220.00, 9),
	(43,'Scaffale in Legno', 'Scaffale in legno per uso domestico, un\'opzione versatile per organizzare gli spazi con gusto.', 70.00, 10),
	(44,'Cassettiera Moderna', 'Cassettiera moderna con 4 cassetti, un elemento pratico e contemporaneo per la tua stanza.', 100.00, 11),
	(45,'Mobile da Bagno Classico', 'Elegante e funzionale, il mobile da bagno classico con lavabo aggiunge stile al tuo spazio dedicato all\'igiene.', 350.00, 12),
	(46,'Sedia da Giardino Moderna', 'Confortevole e moderna, la sedia da giardino in legno è ideale per momenti di relax all\'aperto.', 60.00, 13),
	(47,'Divano in Pelle', 'Raffinato e lussuoso, il divano in pelle color marrone aggiunge un tocco di eleganza al tuo salotto.', 1300.00, 1),
	(48,'Letto Matrimoniale Moderno', 'Letto matrimoniale moderno con contenitore, unisce comfort e praticità in una soluzione di design.', 900.00, 2),
	(49,'Lampada da Soffitto Moderna', 'Illumina con stile grazie alla lampada da soffitto moderna a LED, perfetta per creare atmosfere accoglienti.', 140.00, 3),
	(50,'Tavolo da Cucina Moderno', 'Il tavolo da cucina moderno in acciaio inossidabile è il centro conviviale della tua cucina con stile.', 400.00, 4),
	(51,'Sedia da Giardino Classica', 'Coniuga tradizione e comfort con la sedia da giardino classica in plastica, perfetta per il tuo spazio all\'aperto.', 20.00, 5),
	(52,'Armadio a Sei Ante', 'Massimo spazio di archiviazione con stile, grazie all\'armadio a sei ante in legno di quercia.', 1400.00, 6),
	(53,'Poltrona da Lettura Moderna', 'La poltrona da lettura moderna in tessuto offre un luogo accogliente per immergersi nei tuoi libri preferiti.', 280.00, 7),
	(54,'Divano in Velluto', 'Lussuoso e accogliente, il divano in velluto color blu aggiunge un tocco di ricercatezza al tuo salotto.', 1100.00, 1),
	(55,'Letto Singolo Classico', 'Letto singolo classico in legno, un elemento affascinante per camere con un tocco tradizionale.', 350.00, 2),
	(56,'Lampada da Tavolo Moderna', 'La lampada da tavolo moderna a LED unisce design contemporaneo e illuminazione funzionale.', 60.00, 3),
	(57,'Tavolo da Caffè Classico', 'Tavolo da caffè classico in legno, perfetto per un\'atmosfera accogliente e tradizionale nel tuo salotto.', 180.00, 4),
	(58,'Sedia da Pranzo Classica', 'Comfort e eleganza si incontrano nella sedia da pranzo classica in legno, ideale per cene indimenticabili.', 50.00, 5),
	(59,'Armadio a Sette Ante', 'Massimo spazio di archiviazione con stile, grazie all\'armadio a sette ante in legno di quercia.', 1600.00, 6),
	(60,'Poltrona da Lettura Classica', 'La poltrona da lettura classica in tessuto offre comfort e charme in ogni angolo della tua casa.', 260.00, 7),
	(61,'Divano in Tessuto Moderno', 'Confortevole e moderno, il divano in tessuto moderno color grigio aggiunge stile al tuo soggiorno.', 1000.00, 1),
	(62,'Letto Matrimoniale Classico', 'Letto matrimoniale classico in legno, un elemento affascinante per camere dal tocco tradizionale.', 850.00, 2),
	(63,'Lampada da Soffitto Classica', 'Illumina con eleganza grazie alla lampada da soffitto classica a LED, perfetta per atmosfere raffinate.', 130.00, 3),
	(64,'Tavolo da Cucina Classico', 'Il tavolo da cucina classico in legno è il cuore conviviale della tua cucina, unendo tradizione e funzionalità.', 380.00, 4),
	(65,'Sedia da Giardino Moderna', 'Confortevole e moderna, la sedia da giardino moderna in plastica è ideale per momenti di relax all\'aperto.', 40.00, 5),
	(66,'Armadio a Otto Ante', 'Massimo spazio di archiviazione con stile, grazie all\'armadio a otto ante in legno di faggio.', 1800.00, 6),
	(67,'Poltrona da Ufficio Classica', 'Elegante e funzionale, la poltrona da ufficio classica in pelle offre comfort e stile nella tua area lavorativa.', 220.00, 7);

INSERT INTO prodotti(id, nome, descrizione, prezzo, id_categoria) VALUES
	(1,'Divano Moderno', 'Elegante e confortevole, il divano moderno in pelle aggiunge stile contemporaneo al tuo spazio abitativo.', 1200.00, 1),
	(2,'Letto Matrimoniale', 'Un letto matrimoniale in legno massello per notti serene, con un design che unisce comfort e estetica moderna.', 800.00, 2),
	(3,'Lampada da Tavolo', 'Illumina con stile ogni angolo della tua casa con questa raffinata lampada da tavolo in stile industriale.', 70.00, 3),
	(4,'Tavolo da Pranzo', 'Riunisci famiglia e amici attorno a questo tavolo da pranzo in rovere, unendo funzionalità e design moderno.', 600.00, 4),
	(5,'Sedia da Ufficio', 'Confortevole e funzionale, la sedia da ufficio ergonomica offre supporto per lunghe ore di lavoro.', 150.00, 5),
	(6,'Armadio a Due Ante', 'Organizza il tuo spazio con questo elegante armadio a due ante in legno di pino.', 500.00, 6),
	(7,'Poltrona Reclinabile', 'Rilassati in totale comfort con questa poltrona reclinabile in tessuto, ideale per momenti di puro relax.', 250.00, 7),
	(8,'Credenza Vintage', 'Aggiungi un tocco retrò al tuo arredamento con questa credenza vintage in legno massello.', 700.00, 8),
	(9,'Libreria a Muro', 'Esponi i tuoi libri con stile su questa libreria a muro in metallo e legno, un\'opzione pratica e decorativa.', 200.00, 9),
	(10,'Scaffale Metallico', 'Robusto e moderno, lo scaffale metallico offre un\'opzione di stoccaggio resistente e contemporanea per il garage.', 100.00, 10),
	(11,'Cassettiera Bianca', 'Organizza con stile con questa cassettiera bianca con 5 cassetti, un elemento pratico per ogni stanza.', 80.00, 11),
	(12,'Mobile da Bagno', 'Funzionale e moderno, il mobile da bagno con specchio offre spazio di archiviazione e un design accattivante.', 300.00, 12),
	(13,'Tavolo da Giardino', 'Goditi il tuo spazio esterno con questo tavolo da giardino in rattan, perfetto per pranzi all\'aperto e momenti di relax.', 120.00, 13),
	(14,'Divano Chesterfield', 'Un\'icona di eleganza, il divano Chesterfield in pelle aggiunge un tocco di classe e comfort al tuo salotto.', 1500.00, 1),
	(15,'Letto Singolo', 'Compatto e accogliente, il letto singolo con contenitore è ideale per camere più piccole o come soluzione per gli ospiti.', 400.00, 2),
	(16,'Lampada da Terra', 'Illumina il tuo spazio con stile grazie a questa lampada da terra in stile moderno.', 90.00, 3),
	(17,'Tavolino da Caffè', 'Aggiungi un tocco di praticità al tuo salotto con questo tavolino da caffè in vetro, perfetto per riunioni informali.', 200.00, 4),
	(18,'Sedia da Pranzo', 'Comfort e stile si fondono in questa sedia da pranzo in legno massello, ideale per creare un\'atmosfera accogliente a tavola.', 60.00, 5),
	(19,'Armadio a Tre Ante', 'Massimo spazio e stile con questo armadio a tre ante in legno di quercia, perfetto per organizzare il tuo guardaroba.', 800.00, 6),
	(20,'Poltrona da Lettura', 'Un\'oasi di comfort, la poltrona da lettura in tessuto offre un luogo accogliente per immergersi nei tuoi libri preferiti.', 300.00, 7),
	(21,'Divano in Tessuto', 'Confortevole e moderno, il divano in tessuto color grigio aggiunge calore e stile al tuo soggiorno.', 900.00, 1),
	(22,'Letto a Castello', 'Ottimizza lo spazio con questo pratico letto a castello in metallo, ideale per camere con più occupanti.', 500.00, 2),
	(23,'Lampada da Soffitto', 'Illumina con eleganza ogni angolo della tua casa con questa lampada da soffitto a LED.', 120.00, 3),
	(24,'Tavolo da Cucina', 'Funzionale e accattivante, il tavolo da cucina in acciaio inossidabile è il cuore della tua area gastronomica.', 350.00, 4),
	(25,'Sedia da Giardino', 'Coniuga comodità e resistenza con questa sedia da giardino in plastica, perfetta per momenti all\'aria aperta.', 30.00, 5),
	(26,'Armadio a Quattro Ante', 'Massimo spazio di archiviazione con stile, grazie a questo ampio armadio a quattro ante in legno di faggio.', 1000.00, 6),
	(27,'Poltrona da Ufficio', 'Coniuga comfort e design nella tua area lavorativa con questa poltrona da ufficio in pelle.', 200.00, 7),
	(28,'Credenza Moderna', 'Unisce funzionalità e design contemporaneo, la credenza moderna in MDF è perfetta per l\'organizzazione degli spazi.', 400.00, 8),
	(29,'Libreria a Colonna', 'Ottimizza lo spazio verticale con questa libreria a colonna in legno massello, ideale per esporre libri e oggetti d\'arte.', 250.00, 9),
	(30,'Scaffale in Plastica', 'Leggero e pratico, lo scaffale in plastica offre soluzioni di stoccaggio flessibili in ogni ambiente domestico.', 50.00, 10),
	(31,'Cassettiera in Legno', 'Organizza con stile con questa cassettiera in legno con 3 cassetti, un elemento versatile per diverse stanze.', 120.00, 11),
	(32,'Mobile da Bagno Moderno', 'Unisce funzionalità e design contemporaneo, il mobile da bagno moderno con lavabo è perfetto per lo spazio dedicato all\'igiene personale.', 450.00, 12),
	(33,'Sedia da Giardino', 'Confortevole e resistente alle intemperie, la sedia da giardino in legno è l\'ideale per godersi gli spazi esterni.', 80.00, 13),
	(34,'Divano Classico', 'Elegante e raffinato, il divano classico in tessuto aggiunge un tocco di tradizione al tuo salotto.', 700.00, 1),
	(35,'Letto Singolo Moderno', 'Letto singolo moderno con contenitore, perfetto per ottimizzare lo spazio con stile contemporaneo.', 300.00, 2),
	(36,'Lampada da Parete', 'Illumina con eleganza ogni angolo con la lampada da parete a LED, un elemento moderno e funzionale.', 50.00, 3),
	(37,'Tavolo da Caffè Moderno', 'Tavolo da caffè moderno in vetro, un\'opzione chic per arricchire il tuo salotto con stile.', 150.00, 4),
	(38,'Sedia da Pranzo Moderna', 'Sedia da pranzo moderna in legno, unisce comfort e design contemporaneo per cene indimenticabili.', 40.00, 5),
	(39,'Armadio a Cinque Ante', 'Massimo spazio e stile con l\'armadio a cinque ante in legno di faggio, perfetto per organizzare la tua stanza.', 1200.00, 6),
	(40,'Poltrona da Ufficio Moderna', 'Confortevole e professionale, la poltrona da ufficio moderna in pelle rende il lavoro più piacevole.', 180.00, 7),
	(41,'Credenza Classica', 'Credenza classica in legno massello, un pezzo d\'arredamento che aggiunge charme e praticità.', 500.00, 8),
	(42,'Libreria a Terra', 'Esponi i tuoi libri con stile su questa libreria a terra in metallo e legno, perfetta per un tocco moderno.', 220.00, 9),
	(43,'Scaffale in Legno', 'Scaffale in legno per uso domestico, un\'opzione versatile per organizzare gli spazi con gusto.', 70.00, 10),
	(44,'Cassettiera Moderna', 'Cassettiera moderna con 4 cassetti, un elemento pratico e contemporaneo per la tua stanza.', 100.00, 11),
	(45,'Mobile da Bagno Classico', 'Elegante e funzionale, il mobile da bagno classico con lavabo aggiunge stile al tuo spazio dedicato all\'igiene.', 350.00, 12),
	(46,'Sedia da Giardino Moderna', 'Confortevole e moderna, la sedia da giardino in legno è ideale per momenti di relax all\'aperto.', 60.00, 13),
	(47,'Divano in Pelle', 'Raffinato e lussuoso, il divano in pelle color marrone aggiunge un tocco di eleganza al tuo salotto.', 1300.00, 1),
	(48,'Letto Matrimoniale Moderno', 'Letto matrimoniale moderno con contenitore, unisce comfort e praticità in una soluzione di design.', 900.00, 2),
	(49,'Lampada da Soffitto Moderna', 'Illumina con stile grazie alla lampada da soffitto moderna a LED, perfetta per creare atmosfere accoglienti.', 140.00, 3),
	(50,'Tavolo da Cucina Moderno', 'Il tavolo da cucina moderno in acciaio inossidabile è il centro conviviale della tua cucina con stile.', 400.00, 4),
	(51,'Sedia da Giardino Classica', 'Coniuga tradizione e comfort con la sedia da giardino classica in plastica, perfetta per il tuo spazio all\'aperto.', 20.00, 5),
	(52,'Armadio a Sei Ante', 'Massimo spazio di archiviazione con stile, grazie all\'armadio a sei ante in legno di quercia.', 1400.00, 6),
	(53,'Poltrona da Lettura Moderna', 'La poltrona da lettura moderna in tessuto offre un luogo accogliente per immergersi nei tuoi libri preferiti.', 280.00, 7),
	(54,'Divano in Velluto', 'Lussuoso e accogliente, il divano in velluto color blu aggiunge un tocco di ricercatezza al tuo salotto.', 1100.00, 1),
	(55,'Letto Singolo Classico', 'Letto singolo classico in legno, un elemento affascinante per camere con un tocco tradizionale.', 350.00, 2),
	(56,'Lampada da Tavolo Moderna', 'La lampada da tavolo moderna a LED unisce design contemporaneo e illuminazione funzionale.', 60.00, 3),
	(57,'Tavolo da Caffè Classico', 'Tavolo da caffè classico in legno, perfetto per un\'atmosfera accogliente e tradizionale nel tuo salotto.', 180.00, 4),
	(58,'Sedia da Pranzo Classica', 'Comfort e eleganza si incontrano nella sedia da pranzo classica in legno, ideale per cene indimenticabili.', 50.00, 5),
	(59,'Armadio a Sette Ante', 'Massimo spazio di archiviazione con stile, grazie all\'armadio a sette ante in legno di quercia.', 1600.00, 6),
	(60,'Poltrona da Lettura Classica', 'La poltrona da lettura classica in tessuto offre comfort e charme in ogni angolo della tua casa.', 260.00, 7),
	(61,'Divano in Tessuto Moderno', 'Confortevole e moderno, il divano in tessuto moderno color grigio aggiunge stile al tuo soggiorno.', 1000.00, 1),
	(62,'Letto Matrimoniale Classico', 'Letto matrimoniale classico in legno, un elemento affascinante per camere dal tocco tradizionale.', 850.00, 2),
	(63,'Lampada da Soffitto Classica', 'Illumina con eleganza grazie alla lampada da soffitto classica a LED, perfetta per atmosfere raffinate.', 130.00, 3),
	(64,'Tavolo da Cucina Classico', 'Il tavolo da cucina classico in legno è il cuore conviviale della tua cucina, unendo tradizione e funzionalità.', 380.00, 4),
	(65,'Sedia da Giardino Moderna', 'Confortevole e moderna, la sedia da giardino moderna in plastica è ideale per momenti di relax all\'aperto.', 40.00, 5),
	(66,'Armadio a Otto Ante', 'Massimo spazio di archiviazione con stile, grazie all\'armadio a otto ante in legno di faggio.', 1800.00, 6),
	(67,'Poltrona da Ufficio Classica', 'Elegante e funzionale, la poltrona da ufficio classica in pelle offre comfort e stile nella tua area lavorativa.', 220.00, 7);


INSERT INTO prodotti(nome, prezzo, id_prodotto) VALUES
	('Cuscini Decorativi', 30.00, 1),
	('Pouf in Pelle', 100.00, 1),
	('Tappeto Moderno', 80.00, 1),
	
	('Parure di Lenzuola', 50.00, 2),
	('Comodino Design', 120.00, 2),
	('Lampada da Tavolo in Legno', 40.00, 2),
	
	('Lampadina LED', 10.00, 3),
	('Porta Riviste Moderno', 60.00, 3),
	('Cornice Foto in Metallo', 20.00, 3),
	
	('Set di Piatti Eleganti', 70.00, 4),
	('Centrotavola Moderno', 30.00, 4),
	('Sottobicchieri in Vetro', 15.00, 4),
	
	('Cuscino Ergonomico per Sedia', 25.00,5),
	('Tappetino per Sedia in PVC', 20.00, 5),
	('Supporto Lombare Regolabile', 35.00, 5),
	
	('Scatola Organizer in Legno', 50.00, 6),
	('Specchio da Terra Design', 180.00, 6),
	('Appendiabiti Moderno', 40.00, 6),
	
	('Poggiapiedi Imbottito', 80.00, 7),
	('Coperta Morbida in Pile', 45.00, 7),
	('Cuscino Poggiatesta', 20.00, 7),
	
	('Tavola da Cucina Pieghevole', 60.00, 8),
	('Vassoio Vintage', 25.00, 8),
	('Set di Coltelli da Cucina', 90.00, 8),
	
	('Mensole Moderne', 30.00, 9),
	('Vaso Decorativo', 15.00, 9),
	('Cornice Foto a Parete', 25.00, 9),
	
	('Cestino Portarifiuti', 15.00, 10),
	('Contenitori Organizer Trasparenti', 40.00, 10),
	('Sgabello Pieghevole', 18.00, 10),
	
	('Set di Tovagliette', 25.00, 11),
	('Candeliere Classico', 40.00, 11),
	('Vaso di Fiori Artificiali', 20.00, 11),
	
	('Set di Asciugamani di Design', 35.00, 12),
	('Porta Spazzolino Moderno', 15.00, 12),
	('Set Accessori da Bagno in Ceramica', 50.00, 12),
	
	('Tavolino da Giardino Pieghevole', 50.00, 13),
	('Ombrellone Moderno', 120.00, 13),
	('Cuscini per Sedie da Giardino', 25.00, 13),
	
	('Copridivano in Velluto', 60.00, 14),
	('Cuscino a Forma di Cuore', 18.00,  14),
	('Vaso di Fiori Secchi', 25.00,  14),
	
	('Set di Asciugamani a Righe', 30.00,  15),
	('Portaoggetti Integrato al Letto', 40.00,  15),
	('Appendiabiti da Parete', 15.00,  15),
	
	('Lampada da Terra con Bracci Regolabili', 75.00,  16),
	('Vaso di Fiori in Ceramica', 22.00,  16),
	('Specchio Moderno da Parete', 50.00,  16),
	
	('Tavolino da Salotto in Legno', 120.00,  17),
	('Set di Tovaglioli Eleganti', 28.00,  17),
	('Candelabro in Metallo', 35.00,  17),
	
	('Cuscino Seduta in Paglia', 15.00,  18),
	('Centrotavola Classico', 35.00,  18),
	('Tovaglia a Quadretti', 22.00,  18),
	
	('Set di Appendiabiti in Legno', 40.00,  19),
	('Portaombrelli Design', 70.00,  19),
	('Set di Portaoggetti in Bambù', 25.00,  19),
	
	('Cuscino Lombare Decorativo', 20.00,  20),
	('Lampada da Lettura Flessibile', 30.00,  20),
	('Coperta in Pile Morbido', 40.00,  20),
	
	('Tovaglia Elegante', 35.00,  21),
	('Set di Piatti da Portata', 45.00,  21),
	('Candelabro da Tavolo', 28.00,  21),
	
	('Quadro Moderno Astratto', 60.00,  22),
	('Set di Scatole Organizer Colorate', 18.00,  22),
	('Tappeto da Parete Vintage', 40.00,  22),
	
	('Scaffale Portaoggetti', 25.00,  23),
	('Scatola in Tessuto per Riporre', 15.00,  23),
	('Sgabello da Bar Moderno', 50.00,  23),
	
	('Cuscino Seduta in Pelle', 35.00, 24),
	('Vaso di Fiori in Vetro', 20.00,  24),
	('Tappeto da Cucina Antiscivolo', 18.00,  24),
	
	('Set di Asciugamani da Bagno', 30.00,  25),
	('Sgabello da Giardino Pieghevole', 22.00,  25),
	('Lampada Solare da Giardino', 45.00,  25),
	
	('Copridivano Elastico', 50.00,  26),
	('Set di Tazze da Caffè', 18.00,  26),
	('Ombrellone da Giardino', 120.00,  26),
	
	('Portaoggetti da Parete', 30.00,  27),
	('Lampada da Scrivania Moderna', 40.00,  27),
	('Set di Contenitori in Vetro', 25.00,  27),
	
	('Vaso di Fiori in Porcellana', 28.00,  28),
	('Set di Scatole Organizer in Plastica', 15.00,  28),
	('Tappeto da Cucina Colorato', 18.00,  28),
	
	('Sgabello in Legno Massello', 40.00,  29),
	('Lampada da Tavolo Classica', 25.00,  29),
	('Scatola Portagioie Vintage', 30.00,  29),
	
	('Set di Piatti da Portata', 45.00,  30),
	('Vaso di Fiori in Vetro', 22.00,  30),
	('Centrotavola da Tavolo', 28.00,  30),
	
	('Appendiabiti da Parete Moderno', 30.00,  31),
	('Cornice Foto Design', 18.00,  31),
	('Scatola Organizer in Rattan', 25.00,  31),
	
	('Tappeto da Bagno Morbido', 20.00,  32),
	('Set di Accessori da Bagno in Acciaio', 50.00,  32),
	('Sgabello da Bagno Design', 30.00,  32),
	
	('Cuscino Decorativo Floreale', 18.00, 33),
	('Lampada da Tavolo in Ceramica', 35.00,  33),
	('Candelabro da Terra Moderno', 60.00,  33),
	
	('Tovaglia a Quadretti', 25.00,  34),
	('Set di Posate da Tavola', 40.00, 34),
	('Vaso di Fiori Secchi', 18.00, 34),
	
	('Cornice Foto a Parete', 30.00,  35),
	('Lampada da Terra in Legno', 60.00,  35),
	('Set di Portacandele Moderni', 22.00,  35),
	
	('Scaffale da Parete in Legno', 35.00,  36),
	('Scatola Portariviste Design', 18.00,  36),
	('Orologio da Parete Moderno', 40.00,  36),
	
	('Cuscino Lombare Decorativo', 22.00,  37),
	('Tappeto da Soggiorno', 40.00,  37),
	('Lampada da Tavolo Classica', 28.00,  37),
	
	('Set di Tovagliette in Rattan', 25.00, 38),
	('Vaso di Fiori in Ceramica', 30.00,  38),
	('Centrotavola Moderno', 22.00,  38),
	
	('Scaffale Portaoggetti', 35.00,  39),
	('Cuscino Decorativo Floreale', 18.00,  39),
	('Lampada da Scrivania Moderna', 40.00,  39),
	
	('Scatola Organizer in Tessuto', 15.00, 40),
	('Tappeto da Cucina Antiscivolo', 22.00,  40),
	('Sgabello da Bar in Legno', 50.00, 40),
	
	('Cuscino per Sedia Imbottito', 20.00,  41),
	('Lampada da Tavolo in Vetro', 30.00,  41),
	('Set di Contenitori in Metallo', 35.00, 41),
	
	('Vaso di Fiori in Vetro', 28.00, 42),
	('Set di Scatole Organizer Colorate', 18.00, 42),
	('Tappeto da Cucina Morbido', 25.00,  42),
	
	('Scaffale in Metallo', 30.00,  43),
	('Cuscino Lombare Decorativo', 22.00,  43),
	('Lampada da Terra Moderna', 45.00,  43),
	
	('Set di Tovaglioli Eleganti', 40.00,  44),
	('Vaso di Fiori Secchi', 18.00,  44),
	('Centrotavola da Tavolo', 28.00,  44),
	
	('Appendiabiti da Parete Design', 30.00,  45),
	('Specchio da Bagno Moderno', 60.00,  45),
	('Set Accessori da Bagno in Porcellana', 22.00,  45),
	
	('Tappeto da Bagno Antiscivolo', 20.00, 46),
	('Sgabello da Bagno Design', 35.00,  46),
	('Cuscino per Vasca da Bagno', 18.00,  46),
	
	('Copridivano Elasticizzato', 50.00,  47),
	('Set di Posate da Tavola', 40.00,  47),
	('Candelabro da Tavolo Moderno', 28.00,  47),
	
	('Cornice Foto a Parete', 30.00,  48),
	('Lampada da Terra in Legno', 60.00,  48),
	('Set di Portacandele Moderni', 22.00,  48),
	
	('Scaffale da Parete in Legno', 35.00,  49),
	('Scatola Portariviste Design', 18.00,  49),
	('Orologio da Parete Moderno', 40.00,  49),
	
	('Cuscino Lombare Decorativo', 22.00,  50),
	('Tappeto da Soggiorno', 40.00,  50),
	('Lampada da Tavolo Classica', 28.00,  50),
	
	('Set di Tovagliette in Rattan', 25.00,  51),
	('Vaso di Fiori in Ceramica', 30.00, 51),
	('Centrotavola Moderno', 22.00,  51),
	
	('Scaffale Portaoggetti', 35.00,  52),
	('Cuscino Decorativo Floreale', 18.00, 52),
	('Lampada da Scrivania Moderna', 40.00,  52),
	
	('Scatola Organizer in Tessuto', 15.00,  53),
	('Tappeto da Cucina Antiscivolo', 22.00,  53),
	('Sgabello da Bar in Legno', 50.00,  53),
	
	('Cuscino per Sedia Imbottito', 20.00, 54),
	('Lampada da Tavolo in Vetro', 30.00,  54),
	('Set di Contenitori in Metallo', 35.00, 54),
	
	('Vaso di Fiori in Vetro', 28.00,  55),
	('Set di Scatole Organizer Colorate', 18.00,  55),
	('Tappeto da Cucina Morbido', 25.00,  55),
	
	('Scaffale in Metallo', 30.00,  56),
	('Cuscino Lombare Decorativo', 22.00,  56),
	('Lampada da Terra Moderna', 45.00,  56),
	
	('Set di Tovaglioli Eleganti', 40.00,  57),
	('Vaso di Fiori Secchi', 18.00,  57),
	('Centrotavola da Tavolo', 28.00,  57),
	
	('Appendiabiti da Parete Design', 30.00,  58),
	('Specchio da Bagno Moderno', 60.00,  58),
	('Set Accessori da Bagno in Porcellana', 22.00, 58),
	
	('Tappeto da Bagno Antiscivolo', 20.00, 59),
	('Sgabello da Bagno Design', 35.00,  59),
	('Cuscino per Vasca da Bagno', 18.00,  59),
	
	('Copridivano Elasticizzato', 50.00,  60),
	('Set di Posate da Tavola', 40.00,  60),
	('Candelabro da Tavolo Moderno', 28.00,  60),
	
	('Cornice Foto a Parete', 30.00,  61),
	('Lampada da Terra in Legno', 60.00,  61),
	('Set di Portacandele Moderni', 22.00,  61),
	
	('Scaffale da Parete in Legno', 35.00,  62),
	('Scatola Portariviste Design', 18.00,  62),
	('Orologio da Parete Moderno', 40.00,  62),
	
	('Cuscino Lombare Decorativo', 22.00, 63),
	('Tappeto da Soggiorno', 40.00,  63),
	('Lampada da Tavolo Classica', 28.00,  63),
	
	('Set di Tovagliette in Rattan', 25.00,  64),
	('Vaso di Fiori in Ceramica', 30.00,  64),
	('Centrotavola Moderno', 22.00, 64),
	
	('Scaffale Portaoggetti', 35.00,  65),
	('Cuscino Decorativo Floreale', 18.00,  65),
	('Lampada da Scrivania Moderna', 40.00,  65),
	
	('Scatola Organizer in Tessuto', 15.00,  66),
	('Tappeto da Cucina Antiscivolo', 22.00,  66),
	('Sgabello da Bar in Legno', 50.00,  66),
	
	('Cuscino per Sedia Imbottito', 20.00,  67),
	('Lampada da Tavolo in Vetro', 30.00,  67),
	('Set di Contenitori in Metallo', 35.00,  67);

INSERT INTO immagini_prodotti (path_immagine, id_prodotti) VALUES 
	('divano_moderno.jpg', 1),
	('letto_matrimoniale.jpg', 2),
	('lampada_da_tavolo.webp', 3),
	('tavolo-da-pranzo.jpg', 4),
	('sedia_da_ufficio.webp', 5),
	('armadio_due_ante.webp', 6),
	('poltrona_reclinabile.jpeg', 7),
	('credenza_vintage.jpg', 8),
	('libreria_muro.jpg', 9),
	('scaffale_metallico.webp', 10),
	('cassettiera_bianca.jpg', 11),
	('mobile_bagno.jpg', 12),
	('tavolo_giardino.jpg', 13);
	
INSERT INTO immagini_prodotti (path_immagine, id_prodotti) VALUES 
	('divano_chesterfield.jpeg', 14),
	('letto_singolo.jpg', 15),
	('lampada-da-terra.webp', 16),
	('tavolino_caffe.jpg', 17),
	('sedia-da-pranzo.jpg', 18),
	('armadio_3_ante.jpg', 19),
	('poltrona_lettura.jpeg', 20),
	('divano_tessuto.jpeg', 21),
	('letto-castello.jpg', 22),
	('placeholder.jpg', 23),
	('placeholder.jpg', 24),
	('placeholder.jpg', 25),
	('placeholder.jpg', 26),
	('placeholder.jpg', 27),
	('placeholder.jpg', 28),
	('placeholder.jpg', 29),
	('placeholder.jpg', 30),
	('placeholder.jpg', 31),
	('placeholder.jpg', 32),
	('placeholder.jpg', 33),
	('placeholder.jpg', 34),
	('placeholder.jpg', 35),
	('placeholder.jpg', 36),
	('placeholder.jpg', 37),
	('placeholder.jpg', 38),
	('placeholder.jpg', 39),
	('placeholder.jpg', 40),
	('placeholder.jpg', 41),
	('placeholder.jpg', 42),
	('placeholder.jpg', 43),
	('placeholder.jpg', 44),
	('placeholder.jpg', 45),
	('placeholder.jpg', 46),
	('placeholder.jpg', 47),
	('placeholder.jpg', 48),
	('placeholder.jpg', 49),
	('placeholder.jpg', 50),
	('placeholder.jpg', 51),
	('placeholder.jpg', 52),
	('placeholder.jpg', 53),
	('placeholder.jpg', 54),
	('placeholder.jpg', 55),
	('placeholder.jpg', 56),
	('placeholder.jpg', 57),
	('placeholder.jpg', 58),
	('placeholder.jpg', 59),
	('placeholder.jpg', 60),
	('placeholder.jpg', 61),
	('placeholder.jpg', 62),
	('placeholder.jpg', 63),
	('placeholder.jpg', 64),
	('placeholder.jpg', 65),
	('placeholder.jpg', 66),
	('placeholder.jpg', 67);